# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RssFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('last_fetched', models.DateField()),
                ('errors', models.TextField()),
            ],
        ),
    ]
