# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_harvesting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='errors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rssfeed',
            name='last_fetched',
            field=models.DateField(blank=True, null=True),
        ),
    ]
