# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_harvesting', '0002_auto_20160929_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='country',
            field=models.CharField(default='Malaysia', max_length=32),
        ),
    ]
