# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_harvesting', '0003_rssfeed_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='publication_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
