# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-29 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed_harvesting', '0006_auto_20161229_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed_harvesting.Report')),
                ('compare_one', models.CharField(max_length=50)),
                ('compare_two', models.CharField(max_length=50)),
                ('compare_three', models.CharField(max_length=50)),
            ],
            bases=('feed_harvesting.report',),
        ),
    ]
