# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-05 14:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('feed_harvesting', '0007_comparisonreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='created',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 1, 5, 14, 41, 36, 972788, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rssfeed',
            name='media_type',
            field=models.CharField(choices=[('News', 'News'), ('Blog', 'Blog'), ('Trades', 'Trades'), ('Radio', 'Radio'), ('TV', 'TV'), ('Print', 'Print')], default='News', max_length=16),
        ),
    ]
